application:
  # Título de la aplicación
  title: Posventa

  # El formato a usar para nombrar las páginas. Con este formato se arman el campo 'title' de los encabezados de la página activa.
  title_format: '{app_title}::{page_title}'

  # El url que se usará para armar todos los paths. Por defecto es /. Ponga un valor aquí solo se está
  # usando su aplicacion dentro de un sub path del server (ej: /web)
  #base_url: /

  # Zona horaria usada principalmente para el formato de fechas 
  time_zone: 'Europe/Madrid'
  
  # Canal por defecto para le entrega de contenido
  deliveryChannel: SkyData\Core\Content\HttpDeliveryChannel
  providerChannel: SkyData\Core\Content\FileContentProvider

# Lista de páginas de la aplicación
navigation:
  Home:
    route: /
    icon: /Themes/Jarvis/Styles/main/img/home.png
    title: Inicio

  FichaASP:
    title: Ficha ASP
    class: FichaASP
    route: /ficha_asp
    icon: /Themes/Jarvis/Styles/main/img/start-icons/stats.png
    # TODO: Agregar la gestión de roles
    roles: ASP,DPV
    # TODO: Hacer que las páginas puedan recibir un template distinto al default
    template: main/bootstrap

  Presupuestador:
    title: Presupuestos
    route: /presupuestos
    icon: /Themes/Jarvis/Styles/main/img/start-icons/orders.png

  DetalleCliente:
    title: Resumen del cliente
    route: /detalles/[*:tipo]/[*:id]
    public: false

  ResumenVehiculo:
    title: Ficha Taller
    route: /resumen/[*:bastidor]
    public: false
    icon: /UI/img/ficha_resumen.png
    
  Search:
    title: Resultados de búsqueda
    route: /search/[*:expresion]/[i:nombres]/[i:matriculas]/[i:dni]/[i:telefonos]
    
# Todos los temas de la aplicación.   
themes:
  Jarvis:
    default: true
    cached: false
    debug: false  

#TODO: Agregar soporte al dataType 'image'
# Todos los servicios      
services:
  HTMLServices:
    defaultType: html
    global: true

  PresupuestadorData:
    dataType: json
    #TODO: Hay que programar el código que manejar los headers 
    headers:
      Cache-Control: no-cache, must-revalidate
      Expires: Mon, 01 Jul 1900 00:00:00 GMT

# Definición de rutas especiales de la aplicación
routes:
# Sección de rutas de la aplicacion. No cambiar las siguientes a menos que se sepa que se está haciendo
# ============================== Core routing =========================================
  services: 
      methods: GET|POST|DELETE|PUT
      route: /service/[a:name]/[*:method]/[*:params]?
      target: /Services
# ============================== End core routing =========================================

storage:
  mysql:
    repository:
      server: localhost
      user: root
      password: 
      database: vars_cargas
      port: 3306
    crm:
      server: localhost
      port: 3306
      user: root
      password: qwerty
      database: crm
      
      
      
      